// GENERATED by tools/embed-sheets.mjs - do not edit by hand.
// Sprite sheets embedded as data URIs so there is no runtime fetch and no CORS surface.
// Art: Pixel Art Sprite Mixer by KingBell (CC-BY 4.0) - https://kingbell.itch.io/pixel-sprite-mixer
import type { Archetype } from '../companion/types';
import type { SheetSpec } from './sheet';

export const SHEETS: Partial<Record<Archetype, SheetSpec>> = {

};
