#!/usr/bin/env node
/**
 * Embeds sprite sheets into render/sheets.ts as data URIs.
 *
 * Why a generator and not esbuild's `dataurl` loader: the plugin registry
 * compiles the published sources itself and only understands .ts/.js/.json,
 * so a `.png` import would fail there. Pre-embedding keeps one source tree
 * that builds identically locally and in the registry.
 *
 * Input, per archetype, in assets/sheets/:
 *   <archetype>.png   the trimmed sheet (rows = animations, columns = frames)
 *   <archetype>.json  { frameWidth, frameHeight, animations: { idle: { row, frames }, ... },
 *                       sourcePalette: { skin: ["#..", ...], hair: [...], armour: [...],
 *                                        belt: [...], legs: [...], weapon: [...] } }
 *
 * Run: `yarn embed-sheets`. Commit the generated file.
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(new URL('..', import.meta.url).pathname);
const ASSETS = join(ROOT, 'assets', 'sheets');
const OUT = join(ROOT, 'render', 'sheets.ts');

const ARCHETYPES = ['magician', 'wizard', 'villager', 'monster', 'ogre', 'orc', 'goblin'];
const ROLES = ['skin', 'hair', 'armour', 'belt', 'legs', 'weapon'];

const entries = [];
let totalBytes = 0;

if (existsSync(ASSETS)) {
  for (const file of readdirSync(ASSETS).sort()) {
    if (!file.endsWith('.png')) continue;
    const archetype = file.slice(0, -4);
    if (!ARCHETYPES.includes(archetype)) {
      console.warn(`skipping ${file}: not an archetype (${ARCHETYPES.join(', ')})`);
      continue;
    }
    const specPath = join(ASSETS, `${archetype}.json`);
    if (!existsSync(specPath)) {
      console.warn(`skipping ${file}: no ${archetype}.json next to it`);
      continue;
    }
    const spec = JSON.parse(readFileSync(specPath, 'utf8'));
    if (!Number.isInteger(spec.frameWidth) || !Number.isInteger(spec.frameHeight)) {
      throw new Error(`${archetype}.json: frameWidth/frameHeight must be integers`);
    }
    if (!spec.animations || !spec.animations.idle) {
      throw new Error(`${archetype}.json: animations.idle is required`);
    }
    const sourcePalette = {};
    for (const role of ROLES) {
      if (Array.isArray(spec.sourcePalette?.[role])) sourcePalette[role] = spec.sourcePalette[role];
    }
    const png = readFileSync(join(ASSETS, file));
    totalBytes += png.byteLength;
    entries.push({
      archetype,
      src: `data:image/png;base64,${png.toString('base64')}`,
      frameWidth: spec.frameWidth,
      frameHeight: spec.frameHeight,
      animations: spec.animations,
      sourcePalette,
    });
  }
}

const body = entries
  .map(
    (e) =>
      `  ${e.archetype}: {\n` +
      `    src: '${e.src}',\n` +
      `    frameWidth: ${e.frameWidth},\n` +
      `    frameHeight: ${e.frameHeight},\n` +
      `    animations: ${JSON.stringify(e.animations)},\n` +
      `    sourcePalette: ${JSON.stringify(e.sourcePalette)},\n` +
      `  },`,
  )
  .join('\n');

const source =
  `// GENERATED by tools/embed-sheets.mjs - do not edit by hand.\n` +
  `// Sprite sheets embedded as data URIs so there is no runtime fetch and no CORS surface.\n` +
  `// Art: Pixel Art Sprite Mixer by KingBell (CC-BY 4.0) - https://kingbell.itch.io/pixel-sprite-mixer\n` +
  `import type { Archetype } from '../companion/types';\n` +
  `import type { SheetSpec } from './sheet';\n\n` +
  `export const SHEETS: Partial<Record<Archetype, SheetSpec>> = {\n${body}\n};\n`;

writeFileSync(OUT, source);
console.log(`render/sheets.ts: ${entries.length} sheet(s), ${(totalBytes / 1024).toFixed(1)} kB of PNG embedded`);
